### PR TITLE
Handled the unhealthy state during deployment

### PR DESCRIPTION
**Pull request by parishahla**
Added a warning to inform users about the state of their deployment.
image

### CODE REVIEW

**Comment by eyeamnoob** [comment]
Can we exit the CLI and don't show logs?

**Comment by parishahla** [comment]
But why? IMO users should see the initial logs (if there are any at all). Could you please give me a bit more context on this.

**Comment by eyeamnoob** [comment]
It's a good idea.

**Comment by eyeamnoob** [comment]
If there is nothing left, it can be merged.

**Pull request merged**
