### PR TITLE
ReadOnly Filesystem

### PR DESCRIPTION
**Pull request by jarqvi**

### CODE REVIEW

**Comment by mhemrg** [comment]
I think we shouldn't define a default value for this. So then our backend
can define it.

**Comment by jarqvi** [comment]
I did this on purpose so that someone reading this code would understand the logic of creating the program.

**Comment by mhemrg** [comment]
What about when we decide to disable read only fs for one more platform? We
should release a new version of the cli.

But if we don't pass anything, we can just update our backend logic. So
users won't need to upgrade their clients.

**Comment by jarqvi** [comment]
Oh right,
I will fix it.

**Pull request merged**
